# Generated by Django 5.2 on 2025-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('groseries', 'Groseries'), ('home', 'Home Decor'), ('mobile', 'Phone'), ('fashion', 'Fashion'), ('O', 'Other')], max_length=25),
        ),
    ]
